// Auto-generated by sigmoid_approximation.py on 2026-02-06 15:28:43
// DO NOT EDIT MANUALLY

#pragma once

#include "SigmoidAcceleration.hpp"
#include <array>

/**
 * @file sigmoid_lookup_table_acceleration_100_1000_5.hpp
 * @brief Auto-generated Acceleration Profile
 * 
 * Profile Parameters:
 * - Speed Range: 100 -> 1000 steps/s
 * - Acceleration Time: 0.5 seconds
 * - CPU Frequency: 170.0 MHz
 * - Prescaler: 25 (Timer Frequency: 6538461.54 Hz)
 * - Shift Bits: 10
 * - Segments: 48
 */

// Lookup table with 48 segments
constexpr std::array<AccelerationSegment, 48> acceleration_100_1000_5 = {{
    AccelerationSegment{1, -402432},
    AccelerationSegment{1, -500736},
    AccelerationSegment{1, -617472},
    AccelerationSegment{1, -757760},
    AccelerationSegment{1, -917504},
    AccelerationSegment{1, -1099776},
    AccelerationSegment{1, -1298432},
    AccelerationSegment{1, -1508352},
    AccelerationSegment{1, -1719296},
    AccelerationSegment{1, -1922048},
    AccelerationSegment{1, -2103296},
    AccelerationSegment{1, -2249728},
    AccelerationSegment{1, -2353152},
    AccelerationSegment{3, -2406742},
    AccelerationSegment{1, -2300926},
    AccelerationSegment{1, -2209792},
    AccelerationSegment{1, -2089984},
    AccelerationSegment{1, -1957888},
    AccelerationSegment{1, -1822720},
    AccelerationSegment{1, -1687552},
    AccelerationSegment{1, -1556480},
    AccelerationSegment{1, -1432576},
    AccelerationSegment{1, -1315840},
    AccelerationSegment{1, -1208320},
    AccelerationSegment{1, -1108992},
    AccelerationSegment{1, -1018880},
    AccelerationSegment{1, -935936},
    AccelerationSegment{1, -862208},
    AccelerationSegment{1, -793600},
    AccelerationSegment{2, -703488},
    AccelerationSegment{2, -603648},
    AccelerationSegment{2, -520704},
    AccelerationSegment{2, -451584},
    AccelerationSegment{3, -380586},
    AccelerationSegment{3, -315392},
    AccelerationSegment{3, -263510},
    AccelerationSegment{4, -216064},
    AccelerationSegment{5, -171008},
    AccelerationSegment{5, -134963},
    AccelerationSegment{6, -105642},
    AccelerationSegment{8, -79232},
    AccelerationSegment{10, -56832},
    AccelerationSegment{12, -39253},
    AccelerationSegment{16, -25408},
    AccelerationSegment{23, -14648},
    AccelerationSegment{35, -6933},
    AccelerationSegment{69, -2078},
    AccelerationSegment{33, -558}

}};

// Profile instance for easy access
constexpr SigmoidAccelerationProfile acceleration_100_1000_5_profile(
    6538461,   // timer_freq_hz
    25,        // prescaler
    65383,     // initial_arr
    100,       // start_speed_steps_per_s
    1000,      // target_speed_steps_per_s
    10,        // shift_bits
    48         // num_segments
);
